baseURL = "https://example.org/"
languageCode = "en-us"
title = "A Kavu Garden"
theme = "kavu"
themesdir = "../../"
copyright = "Example Gardener"
relativeURLs = false
canonifyURLs = false

[params]
  name = "Example Gardener"
  description = "A demo digital garden built with the Kavu Hugo theme."
  initials = "kavu"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/stultus/kavu"
    icon = "fab fa-github"


[menu]
  [[menu.main]]
    name = "notes"
    url = "/notes/"
    weight = 1
  [[menu.main]]
    name = "github"
    url = "https://github.com/stultus/kavu"
    weight = 2


[taxonomies]
  tag = "tags"


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    noClasses = false
    style = 'monokai'

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

enableRobotsTXT = true
